### ISSUE TITLE
Transform variables naming convention 

### ISSUE THREAD

**Issue by sayali-purdue** [GT-RAIL/derail-fetchit-public#1]
I was statically reviewing the code. During the review, I observed that two naming conventions have been followed for the variables representing transform in lookupTransform function calls:

(1) A_to_B: where, A is a target frame (i.e. frame_id) and B is a source frame (i.e. child_frame_id)
For example: In file 'manipulation_actions/src/InHandLocalizer.cpp' (line #473)
```
geometry_msgs::TransformStamped gripper_to_object_transform_msg = tf_buffer.lookupTransform("gripper_link",
                                                                                                "object_frame",
                                                                                                ros::Time(0),
                                                                                                ros::Duration(1.0));
```

(2) A_to_B: where, A is a source frame (i.e. child_frame_id) and B is a target frame (i.e. frame_id)
For example: In file manipulation_actions/src/SchunkGearGrasper.cpp (line #251)
```
geometry_msgs::TransformStamped grasp_to_base_transform = tf_buffer.lookupTransform("base_link",
                                                                                           grasp_pose.header.frame_id,
                                                                                           ros::Time(0),
                                                                                           ros::Duration(1.0));
```

As per the lookupTransform definition, the transform object stores the transform from target frame to source frame. Therefore, I think the transform variable name convention in case(1) above gives the clear meaning of what is stored in that transform variable.  A third user may just assume that the meaningful variable name A_to_B represents the transform from frame A to frame B. Further, following two different naming conventions may lead to confusions or issues during code maintenance/reuse in future.

Would really appreciate if you could please describe your perspective behind using two different naming conventions, and your views on its effects on code maintainability/reuse in future.

Thank you.

**Comment by banerjs** [comment]
Good catch on that. I agree that a convention on naming is super important, especially as a code base grows and the number of collaborators on it increases.

What you're seeing is mostly a result of multiple people in a research lab conducting a month (maybe two) long hackathon and integrating code from various internal projects that might have had different naming conventions. We did try to follow best practices during development including code-reviews, CI, CT, etc. Unfortunately standardizing naming conventions was not something we had the bandwidth to do. You could say we adopted a more decentralized approach of ensuring that conventions were followed at integration points, but conventions within packages or even within files were more laissez-faire. The approach worked for us, but is definitely not something that I think applies in all applications.
